# Generated by Django 5.1 on 2024-09-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_pledge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='Project',
            new_name='project',
        ),
    ]
