# Generated by Django 5.1 on 2024-11-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_pledge_supporter_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_funded_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
