# Generated by Django 5.1 on 2024-11-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_current_funded_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='current_funded_amount',
            field=models.IntegerField(),
        ),
    ]
